### ISSUE TITLE
Question about the Role of GNN-Based Dynamics Model during Inference

### ISSUE THREAD

**Issue by pengzhi1998** [hshi74/robocook#3]
Thank you for open-sourcing this great work! I would like to ask you about the role of the GNN-based dynamics model outlined in your paper. 

In the paper's introduction, you mentioned "_**we combine a PointNet-based tool classification module with learned dynamics models to determine the most appropriate tool to use at the current task stage**_", while in Section 6.1, it appears that both the `Tool Predictor` and `Policy Network` operate based on the defined target or sub-target point clouds, rather than on predictions from the dynamics model. Thus, I'm a little bit confused about the usage of this GNN-based dynamics model during deployment and wonder if I might have misunderstood the implementation details. 

I appreciate your precious time and assistance in clarifying this!

**Comment by hshi74** [comment]
Hi Pengzhi,
Thank you for your inquiry. To clarify, the GNN-based dynamics model is used to create a synthetic dataset for training the policy network. You can consider it as a learned simulator that generates a huge offline synthetic dataset to train the policy. The function of the tool predictor, which selects the next tool, does not factor into the understanding of the dynamics. For more details, please refer to paragraphs 3-5 on page 5 and the left section of Figure 3(b) in our paper.

**Comment by pengzhi1998** [comment]
Thank you Haochen for your quick reply and clear explanation!
