### ISSUE TITLE
Regarding the 3D models of the robot tools

### ISSUE THREAD

**Issue by weiweigu1998** [hshi74/robocook#4]
Hello Haochen,
Firstly, thank you very much for contributing such interesting work to the community. I am working on a paper on robot learning in the kitchen domain, and I found the tools that you designed for the robot being very useful. We want to use a similar tool design as yours in our paper. However, I could only find the 3D model of 8 of the 15 tools of your paper. Additionally, the holder part of the rollers and pressing tools do not present in the stl files. I wonder if it is possible for you to also open source those 3D models.

Your help is much appreciated!

**Comment by hshi74** [comment]
Hi Weiwei,

Thanks for reaching out. I have shared the tools in [this link](https://drive.google.com/file/d/1ejcsANuosBnDQvAV-n1OenUGkj-gZOpn/view?usp=sharing). You can find all the tool models in this blender file.

I have also updated the README to share the models.

Hope this is helpful!

Haochen
