### ISSUE TITLE
Question regarding the purpose of the `memory` input to the DynamicsPredictor 

### ISSUE THREAD

**Issue by CWEzio** [hshi74/robocook#5]
Hi Haochen,

Thank you for open-sourcing your work. I have a question regarding the `memory` input to the DynamicsPredictor. This `memory` is treated as the attribute of each particle. However, it seems that during training, this `memory` is always a zero tensor. Could you please explain the intended purpose and functionality of this `memory` input?

Thank you very much in advance!

**Comment by hshi74** [comment]
Hi Chen,

Thanks for bringing up this question. This is actually a historical artifact of the original DPI-nets implementation when Yunzhu tried different things. Now it's simply a placeholder.

Hope this makes sense!

Haochen
