### ISSUE TITLE
How to get camera extrinsic and intrinsic parameter?

### ISSUE THREAD

**Issue by oym1994** [hshi74/robocook#6]
Hi, thanks for your great job. I want to use this data to train a 3D policy where camera intrinsic and extrinsic parameter are needed but unfortunately I cant see this information in the raw data. So can you provide this information or tell how to get these？

Thanks for your attention and wait for your kind response!

**Comment by hshi74** [comment]
Hi, thanks for reaching out!

I've attached the camera extrinsic parameters in [cam_pose.json](https://github.com/user-attachments/files/16192960/cam_pose.json). The script to load it looks like this:

```
from transforms3d.quaternions import *

DEPTH_OPTICAL_FRAME_POSE = [0, 0, 0, 0.5, -0.5, 0.5, -0.5]

with open(os.path.join("/path/to/cam_pose.json"), "r") as f:
    cam_pose_dict = json.load(f)

EXTRINSICS = [np.eye(4) for _ in range(4)]
for i in range(4):
    EXTRINSICS[i][:3, :3] = quat2mat(
        cam_pose_dict[f"cam_{i+1}"]["orientation"]
    ) @ quat2mat(DEPTH_OPTICAL_FRAME_POSE[3:])
    EXTRINSICS[i][:3, 3] = np.array(cam_pose_dict[f"cam_{i+1}"]["position"])
    EXTRINSICS[i] = EXTRINSICS[i].astype(np.float32)

INTRINSICS = np.array(
    [
        [891.4971313476562, 0.0, 651.0776977539062],
        [0.0, 891.4971313476562, 357.4739990234375],
        [0.0, 0.0, 1.0],
    ],
    dtype=np.float32,
)
WIDTH = 1280
HEIGHT = 720
```
The intrinsic parameters are also included.

It has been a while so I'm not 100% sure if this works. Let me know if it doesn't!

**Comment by oym1994** [comment]
Thank you very much!
