### ISSUE TITLE
Question about Tool Preprocess

### ISSUE THREAD

**Issue by Boey-li** [hshi74/robocook#7]
Hello Haochen, 

Thanks for your great work. I am wondering how you preprocess the tool from point cloud. Have you performed sampling for tool point cloud as well? If so, could you please provide more details here? 

I looked through your code and found that you have performed a "o3d.geometry.TriangleMesh.sample_points_poisson_disk" to the tool mesh with 10,000 points but your data visualization seems have less points on the tools. 

Thanks!

**Comment by hshi74** [comment]
If I remember correctly, I ran the farthest point sampling after sampling from a Poisson disk to reduce the number of points on the tool to a fixed number. Let me know if this is not true in the code, and please include a link to the code in that case.

**Comment by Boey-li** [comment]
Thanks for your quick response! I only see the tool processing in [[perception/sample.py](https://github.com/hshi74/robocook/blob/ca46ba6d58ef0fce89a9ebcb03c86309a8291d40/perception/sample.py)] and did not see the fps for tool. Do you remember which part you implemented it? And where I can find the detailed parameters for tool fps?

**Comment by hshi74** [comment]
[Here](https://github.com/hshi74/robocook/blob/ca46ba6d58ef0fce89a9ebcb03c86309a8291d40/scripts/perception/revise_tool_repr.py#L108) is an example. Also, now I remember that I preprocessed the tools into points and stored them in files such as [this one](https://github.com/hshi74/robocook/blob/ca46ba6d58ef0fce89a9ebcb03c86309a8291d40/geometries/reprs/gripper_l_points.npy) to improve speed.

**Comment by Boey-li** [comment]
Thank you so much!!!!
